2020-08-16 02:46:07,072 - INFO - get_financial_statement.py - __main__ - <module> - Unnamed: 0                                                8208
CIK                                                     886475
Company_Name                                      'mktg, inc.'
Form_Type                                                 10-Q
Date_Filed                                          2012-02-03
Filename            edgar/data/886475/0001019056-12-000109.txt
File_Path             edgar/data/886475/000101905612000109.txt
accession_number                          0001019056-12-000109
year                                                      2012
QT                                                        QTR1
Name: 0, dtype: object
2020-08-16 02:46:07,075 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - normal_url: https://www.sec.gov/Archives/edgar/data/886475/000101905612000109/index.json
2020-08-16 02:46:10,935 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - File Path: https://www.sec.gov/Archives/edgar/data/886475/000101905612000109/FilingSummary.xml
2020-08-16 02:46:12,193 - ERROR - get_financial_statement.py - __main__ - <module> - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request\n    httplib_response = conn.getresponse(buffering=True)\n', "TypeError: getresponse() got an unexpected keyword argument 'buffering'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "src/get_financial_statement.py", line 268, in <module>\n    master_reports = __get_report_dict(xml_summary)\n', '  File "src/get_financial_statement.py", line 69, in __get_report_dict\n    content = requests.get(xml_summary).content\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse\n    response.begin()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n', '  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read\n    return self._sslobj.read(len, buffer)\n', 'KeyboardInterrupt\n']['  File "src/get_financial_statement.py", line 268, in <module>\n    master_reports = __get_report_dict(xml_summary)\n', '  File "src/get_financial_statement.py", line 69, in __get_report_dict\n    content = requests.get(xml_summary).content\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse\n    response.begin()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n', '  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read\n    return self._sslobj.read(len, buffer)\n']
2020-08-16 02:46:12,194 - INFO - get_financial_statement.py - __main__ - <module> - Unnamed: 0                                                 1120
CIK                                                     1084869
Company_Name                              1 800 FLOWERS COM INC
Form_Type                                                  10-Q
Date_Filed                                           2012-02-10
Filename            edgar/data/1084869/0001104659-12-008502.txt
File_Path             edgar/data/1084869/000110465912008502.txt
accession_number                           0001104659-12-008502
year                                                       2012
QT                                                         QTR1
Name: 1, dtype: object
2020-08-16 02:46:12,198 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - normal_url: https://www.sec.gov/Archives/edgar/data/1084869/000110465912008502/index.json
2020-08-16 02:46:13,058 - ERROR - get_financial_statement.py - __main__ - <module> - ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request\n    httplib_response = conn.getresponse(buffering=True)\n', "TypeError: getresponse() got an unexpected keyword argument 'buffering'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse\n    response.begin()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n', '  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read\n    return self._sslobj.read(len, buffer)\n', 'KeyboardInterrupt\n']['  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse\n    response.begin()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n', '  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read\n    return self._sslobj.read(len, buffer)\n']
2020-08-16 02:46:13,059 - INFO - get_financial_statement.py - __main__ - <module> - Unnamed: 0                                                  72
CIK                                                     100412
Company_Name                250 WEST 57TH ST ASSOCIATES L.L.C.
Form_Type                                                 10-Q
Date_Filed                                          2012-02-13
Filename            edgar/data/100412/0001193125-12-054970.txt
File_Path             edgar/data/100412/000119312512054970.txt
accession_number                          0001193125-12-054970
year                                                      2012
QT                                                        QTR1
Name: 9, dtype: object
2020-08-16 02:46:13,062 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - normal_url: https://www.sec.gov/Archives/edgar/data/100412/000119312512054970/index.json
2020-08-16 02:46:13,327 - ERROR - get_financial_statement.py - __main__ - <module> - ['Traceback (most recent call last):\n', '  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request\n    self._validate_conn(conn)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn\n    conn.connect()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 284, in connect\n    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket\n    return context.wrap_socket(sock, server_hostname=server_hostname)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\n', 'KeyboardInterrupt\n']['  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request\n    self._validate_conn(conn)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn\n    conn.connect()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 284, in connect\n    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket\n    return context.wrap_socket(sock, server_hostname=server_hostname)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\n']
2020-08-16 02:46:13,328 - INFO - get_financial_statement.py - __main__ - <module> - Unnamed: 0                                                 1554
CIK                                                     1118974
Company_Name                                         30DC, INC.
Form_Type                                                  10-Q
Date_Filed                                           2012-01-31
Filename            edgar/data/1118974/0001065949-12-000012.txt
File_Path             edgar/data/1118974/000106594912000012.txt
accession_number                           0001065949-12-000012
year                                                       2012
QT                                                         QTR1
Name: 10, dtype: object
2020-08-16 02:46:13,331 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - normal_url: https://www.sec.gov/Archives/edgar/data/1118974/000106594912000012/index.json
2020-08-16 02:46:13,498 - ERROR - get_financial_statement.py - __main__ - <module> - ['Traceback (most recent call last):\n', '  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request\n    self._validate_conn(conn)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn\n    conn.connect()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 284, in connect\n    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket\n    return context.wrap_socket(sock, server_hostname=server_hostname)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\n', 'KeyboardInterrupt\n']['  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request\n    self._validate_conn(conn)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn\n    conn.connect()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 284, in connect\n    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket\n    return context.wrap_socket(sock, server_hostname=server_hostname)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\n']
2020-08-16 02:46:13,500 - INFO - get_financial_statement.py - __main__ - <module> - Unnamed: 0                                                 2155
CIK                                                     1221554
Company_Name                           3Power Energy Group Inc.
Form_Type                                                  10-Q
Date_Filed                                           2012-02-21
Filename            edgar/data/1221554/0001144204-12-010127.txt
File_Path             edgar/data/1221554/000114420412010127.txt
accession_number                           0001144204-12-010127
year                                                       2012
QT                                                         QTR1
Name: 13, dtype: object
2020-08-16 02:46:13,506 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - normal_url: https://www.sec.gov/Archives/edgar/data/1221554/000114420412010127/index.json
2020-08-16 02:46:13,675 - ERROR - get_financial_statement.py - __main__ - <module> - ['Traceback (most recent call last):\n', '  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request\n    self._validate_conn(conn)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn\n    conn.connect()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 284, in connect\n    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket\n    return context.wrap_socket(sock, server_hostname=server_hostname)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\n', 'KeyboardInterrupt\n']['  File "src/get_financial_statement.py", line 267, in <module>\n    xml_summary = __get_xml_summary(path_to_file)\n', '  File "src/get_financial_statement.py", line 51, in __get_xml_summary\n    content = requests.get(normal_url).json()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 70, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 413, in send\n    resp = conn.urlopen(\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request\n    self._validate_conn(conn)\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn\n    conn.connect()\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/connection.py", line 284, in connect\n    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,\n', '  File "/usr/local/lib/python3.8/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket\n    return context.wrap_socket(sock, server_hostname=server_hostname)\n', '  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n', '  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\n']
2020-08-16 02:46:13,677 - INFO - get_financial_statement.py - __main__ - <module> - Unnamed: 0                                                7404
CIK                                                     812149
Company_Name                                 4NET SOFTWARE INC
Form_Type                                                 10-Q
Date_Filed                                          2012-02-13
Filename            edgar/data/812149/0001144204-12-007554.txt
File_Path             edgar/data/812149/000114420412007554.txt
accession_number                          0001144204-12-007554
year                                                      2012
QT                                                        QTR1
Name: 17, dtype: object
2020-08-16 02:46:13,681 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - normal_url: https://www.sec.gov/Archives/edgar/data/812149/000114420412007554/index.json
2020-08-16 02:46:15,294 - INFO - get_financial_statement.py - __main__ - __get_xml_summary - File Path: https://www.sec.gov/Archives/edgar/data/812149/000114420412007554/FilingSummary.xml
2020-08-16 02:46:16,497 - INFO - get_financial_statement.py - __main__ - __get_statements_data - statement_url is https://www.sec.gov/Archives/edgar/data/812149/000114420412007554/R3.htm
2020-08-16 02:46:17,535 - INFO - get_financial_statement.py - __main__ - __get_statements_data - statement_url is https://www.sec.gov/Archives/edgar/data/812149/000114420412007554/R4.htm
2020-08-16 02:46:20,206 - INFO - get_financial_statement.py - __main__ - __get_statements_data - statement_url is https://www.sec.gov/Archives/edgar/data/812149/000114420412007554/R5.htm
